// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NNice.DAL;

namespace NNice.DAL.Migrations
{
    [DbContext(typeof(NNiceContext))]
    [Migration("20200529170404_ModifyPartyID")]
    partial class ModifyPartyID
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NNice.Common.Models.AccountModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Avatar");

                    b.Property<string>("Password");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired();

                    b.Property<int>("Role")
                        .HasMaxLength(256);

                    b.Property<string>("Token");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Password = "admin",
                            PasswordHash = new byte[] { 140, 105, 118, 229, 181, 65, 4, 21, 189, 233, 8, 189, 77, 238, 21, 223, 177, 103, 169, 200, 115, 252, 75, 184, 168, 31, 111, 42, 180, 72, 169, 24 },
                            PasswordSalt = new byte[] { 140, 105, 118, 229, 181, 65, 4, 21, 189, 233, 8, 189, 77, 238, 21, 223, 177, 103, 169, 200, 115, 252, 75, 184, 168, 31, 111, 42, 180, 72, 169, 24 },
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            ID = 2,
                            Password = "accountant",
                            PasswordHash = new byte[] { 41, 216, 201, 158, 194, 91, 39, 16, 7, 240, 94, 172, 232, 126, 192, 9, 89, 116, 102, 135, 170, 150, 237, 120, 61, 215, 162, 243, 191, 219, 57, 139 },
                            PasswordSalt = new byte[] { 41, 216, 201, 158, 194, 91, 39, 16, 7, 240, 94, 172, 232, 126, 192, 9, 89, 116, 102, 135, 170, 150, 237, 120, 61, 215, 162, 243, 191, 219, 57, 139 },
                            Role = 3,
                            Username = "accountant"
                        },
                        new
                        {
                            ID = 3,
                            Password = "Cashier",
                            PasswordHash = new byte[] { 174, 156, 136, 76, 231, 55, 219, 170, 118, 106, 60, 149, 183, 112, 25, 116, 217, 25, 109, 180, 17, 193, 206, 169, 176, 54, 192, 68, 127, 169, 163, 151 },
                            PasswordSalt = new byte[] { 174, 156, 136, 76, 231, 55, 219, 170, 118, 106, 60, 149, 183, 112, 25, 116, 217, 25, 109, 180, 17, 193, 206, 169, 176, 54, 192, 68, 127, 169, 163, 151 },
                            Role = 2,
                            Username = "Cashier"
                        });
                });

            modelBuilder.Entity("NNice.Common.Models.ComboDetailModel", b =>
                {
                    b.Property<int>("CBID");

                    b.Property<int>("ProductID");

                    b.HasKey("CBID", "ProductID");

                    b.ToTable("ComboDetails");
                });

            modelBuilder.Entity("NNice.Common.Models.ComboModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<double>("UnitPrice");

                    b.HasKey("ID");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("NNice.Common.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountID");

                    b.Property<string>("Address")
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("Salary");

                    b.HasKey("ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("NNice.Common.Models.InventoryDetailModel", b =>
                {
                    b.Property<int>("InventoryID");

                    b.Property<int>("MaterialID");

                    b.HasKey("InventoryID", "MaterialID");

                    b.ToTable("inventoryDetailModels");
                });

            modelBuilder.Entity("NNice.Common.Models.InventoryModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<double>("TotalAmount");

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.ToTable("inventories");
                });

            modelBuilder.Entity("NNice.Common.Models.InvoiceDetailModel", b =>
                {
                    b.Property<int>("InvoiceID");

                    b.Property<int>("ProductID");

                    b.HasKey("InvoiceID", "ProductID");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("NNice.Common.Models.InvoiceModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BookingParty");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("EndTime");

                    b.Property<int?>("PartyID");

                    b.Property<int>("RoomID");

                    b.Property<DateTime>("StartTime");

                    b.Property<double>("TotalAmount");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("NNice.Common.Models.MaterialModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("InventoryNumber");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<double>("UnitPrice");

                    b.HasKey("ID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("NNice.Common.Models.PartyModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Deposit");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.Property<int>("RoomID");

                    b.HasKey("ID");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("NNice.Common.Models.ProductDetailModel", b =>
                {
                    b.Property<int>("ProductID");

                    b.Property<int>("MaterialID");

                    b.HasKey("ProductID", "MaterialID");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("NNice.Common.Models.ProductModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("UnitPrice");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("NNice.Common.Models.RoomModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity");

                    b.Property<bool>("IsAvailable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("NNice.Common.Models.WorkShiftModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ShiftNumber");

                    b.Property<DateTime>("WorkDate");

                    b.HasKey("ID");

                    b.ToTable("WorkShifts");
                });
#pragma warning restore 612, 618
        }
    }
}
