// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NNice.DAL;

namespace NNice.DAL.Migrations
{
    [DbContext(typeof(NNiceContext))]
    [Migration("20200526182041_AddPasswordProperty")]
    partial class AddPasswordProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NNice.Common.Models.AccountModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Avatar");

                    b.Property<string>("Password");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired();

                    b.Property<int>("Role")
                        .HasMaxLength(256);

                    b.Property<string>("Token");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("NNice.Common.Models.ComboDetailModel", b =>
                {
                    b.Property<int>("CBID");

                    b.Property<int>("ProductID");

                    b.HasKey("CBID", "ProductID");

                    b.ToTable("ComboDetails");
                });

            modelBuilder.Entity("NNice.Common.Models.ComboModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<double>("UnitPrice");

                    b.HasKey("ID");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("NNice.Common.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountID");

                    b.Property<string>("Address")
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("Salary");

                    b.HasKey("ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("NNice.Common.Models.InventoryDetailModel", b =>
                {
                    b.Property<int>("InventoryID");

                    b.Property<int>("MaterialID");

                    b.HasKey("InventoryID", "MaterialID");

                    b.ToTable("inventoryDetailModels");
                });

            modelBuilder.Entity("NNice.Common.Models.InventoryModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<double>("TotalAmount");

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.ToTable("inventories");
                });

            modelBuilder.Entity("NNice.Common.Models.InvoiceDetailModel", b =>
                {
                    b.Property<int>("InvoiceID");

                    b.Property<int>("ProductID");

                    b.HasKey("InvoiceID", "ProductID");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("NNice.Common.Models.InvoiceModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("EndTime");

                    b.Property<int>("RoomID");

                    b.Property<DateTime>("StartTime");

                    b.Property<double>("TotalAmount");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("NNice.Common.Models.MaterialModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("InventoryNumber");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<double>("UnitPrice");

                    b.HasKey("ID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("NNice.Common.Models.PartyModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Deposit");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.Property<int>("RoomID");

                    b.HasKey("ID");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("NNice.Common.Models.ProductDetailModel", b =>
                {
                    b.Property<int>("ProductID");

                    b.Property<int>("MaterialID");

                    b.HasKey("ProductID", "MaterialID");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("NNice.Common.Models.ProductModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("UnitPrice");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("NNice.Common.Models.RoomModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity");

                    b.Property<bool>("IsAvailable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("NNice.Common.Models.WorkShiftModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ShiftNumber");

                    b.Property<DateTime>("WorkDate");

                    b.HasKey("ID");

                    b.ToTable("WorkShifts");
                });
#pragma warning restore 612, 618
        }
    }
}
